accounts/urls.py
from django.urls import path
from django.contrib.auth.views import LoginView, LogoutView
from accounts.views import signup

urlpatterns = [
    path("login/", LoginView.as_view(), name="login"),
    path("logout/", LogoutView.as_view(), name="logout"),
    path("signup/", signup, name="signup"),
]

projects/urls.py
from django.urls import path
from projects.views import (
    ProjectListView,
    ProjectDetailView,
    ProjectCreateView,
)  # noqa

urlpatterns = [
    path("", ProjectListView.as_view(), name="list_projects"),
    path("<int:pk>/", ProjectDetailView.as_view(), name="show_project"),
    path("create/", ProjectCreateView.as_view(), name="create_project"),
]

tasks/urls.py
from django.urls import path
from tasks.views import AddFormView, TaskListView, TaskUpdateView

urlpatterns = [
    path("create/", AddFormView.as_view(), name="create_task"),
    path("mine/", TaskListView.as_view(), name="show_my_tasks"),
    path("<int:pk>/complete/", TaskUpdateView.as_view(), name="complete_task"),
]

tracker/urls.py
from django.contrib import admin
from django.urls import path, include, reverse_lazy
from django.views.generic import RedirectView

urlpatterns = [
    path("admin/", admin.site.urls),
    path("projects/", include("projects.urls")),
    path(
        "",
        RedirectView.as_view(url=reverse_lazy("list_projects")),
        name=("home"),
    ),  # noqa
    path("accounts/", include("accounts.urls")),
    path("tasks/", include("tasks.urls")),
]

accounts/models.py
# from django.db import models

# Create your models here.

projects/models.py
from django.db import models
from django.conf import settings

USER_MODEL = settings.AUTH_USER_MODEL


# Create your models here.
class Project(models.Model):
    name = models.CharField(max_length=200)
    description = models.TextField()
    members = models.ManyToManyField(USER_MODEL, related_name="projects")

    def __str__(self):
        return self.name

tasks/models.py
from django.db import models
from projects.models import Project
from django.conf import settings

USER_MODEL = settings.AUTH_USER_MODEL


# Create your models here.
class Task(models.Model):
    name = models.CharField(max_length=200)
    start_date = models.DateTimeField()
    due_date = models.DateTimeField()
    is_completed = models.BooleanField(default=False)
    project = models.ForeignKey(
        Project, on_delete=models.CASCADE, related_name="tasks"
    )  # noqa
    assignee = models.ForeignKey(
        USER_MODEL, null=True, related_name="tasks", on_delete=models.SET_NULL
    )  # noqa

    def __str__(self):
        return self.name

tasks/forms.py
from django import forms
from tasks.models import Task


class AddForm(forms.ModelForm):
    class Meta:
        model = Task
        fields = ["name", "start_date", "due_date", "project", "assignee"]

accounts/views.py
from django.shortcuts import render, redirect
from django.contrib.auth.forms import UserCreationForm
from django.contrib.auth.models import User
from django.contrib.auth import login

# Create your views here.


def signup(request):
    if request.method == "POST":
        form = UserCreationForm(request.POST)
        if form.is_valid():
            username = request.POST.get("username")
            password = request.POST.get("password")
            user = User.objects.create_user(
                username=username,
                password=password,
            )
            user.save()
            login(request, user)
            return redirect("home")
    else:
        form = UserCreationForm(request.POST)
    context = {"form": form}
    return render(request, "registration/signup.html", context)

projects/views.py
from django.shortcuts import redirect
from django.views.generic.list import ListView
from django.views.generic.detail import DetailView
from django.views.generic.edit import CreateView
from projects.models import Project
from django.contrib.auth.mixins import LoginRequiredMixin
from tasks.models import Task

# Create your views here.


class ProjectListView(LoginRequiredMixin, ListView):
    model = Project
    template_name = "project_listview.html"

    def get_queryset(self):
        return Project.objects.filter(members=self.request.user)


class ProjectDetailView(LoginRequiredMixin, DetailView):
    model = Task
    template_name = "project_detailview.html"

    def get_queryset(self):
        return Project.objects.filter(members=self.request.user)


class ProjectCreateView(LoginRequiredMixin, CreateView):
    model = Project
    template_name = "project_create.html"
    fields = ["name", "description", "members"]

    def form_valid(self, form):
        item = form.save()
        item.assignee = self.request.user
        item.save()
        return redirect("show_project", item.pk)

tasks/views.py
from django.shortcuts import redirect
from .forms import AddForm
from django.views.generic.edit import FormView
from django.contrib.auth.mixins import LoginRequiredMixin
from django.views.generic.list import ListView
from .models import Task
from django.views.generic.edit import UpdateView
from django.urls import reverse_lazy


class AddFormView(LoginRequiredMixin, FormView):
    template_name = "task_create.html"
    form_class = AddForm

    def form_valid(self, form):
        item = form.save()
        item.user_property = self.request.user
        item.save()
        return redirect("show_project", item.pk)


class TaskListView(LoginRequiredMixin, ListView):
    model = Task
    template_name = "task_listview.html"

    def get_queryset(self):
        return Task.objects.filter(assignee=self.request.user)


class TaskUpdateView(LoginRequiredMixin, UpdateView):
    model = Task
    template_name = "task_listview.html"
    fields = ["is_completed"]
    success_url = reverse_lazy("show_my_tasks")

projects/templates/base.html
{% load static %}
<!doctype html>
<html>
    <head>
        <meta charset="UTF-8">
        <meta http-equiv="X-UA-Compatible" content="IE=edge">
        <meta name="viewport" content="width=device-width, initial-scale=1.0">
        <title>Tracker</title>
    </head>
    <body>
        <header>
            <nav>
                <ul>
                    {% if user.is_authenticated %}
                        <li>
                            <a href="{% url 'show_my_tasks' %}">My tasks</a>
                        </li>
                        <li>
                            <a href="{% url 'list_projects' %}">My projects</a>
                        </li>
                        <li>
                            <a href="{% url 'logout' %}">Logout</a>
                        </li>
                    {% else %}
                        <li>
                            <a href="{% url 'login' %}">Login</a>
                        </li>
                        <li>
                            <a href="{% url 'signup' %}">signup</a>
                        </li>
                    {%endif%}
                </ul>
            </nav>
        </header>
        {%block content%}
        {%endblock content%}
    </body>
</html>

projects/templates/project_create.html
{%extends 'base.html'%}
{%block content%}
    <main>
        <div>
            <h1>Create a new project</h1>
            <form method="POST">
                {% csrf_token %}
                {{form.as_p}}
                <button type="submit">Create</button>
            </form>
        </div>
    </main>
{%endblock content%}

projects/templates/project_detailview.html
{%extends 'base.html'%}
{%block content%}
    {%load markdownify%}
    <main>
        <div>
            <p><a href="{%url 'create_task'%}">Create a new task</a></p>
            <h1>{{project.name}}</h1>
            <p>{{ project.description|markdownify }}</p>
            <h2>Tasks</h2>
            {%if project.tasks.all|length > 0%}
                <table>
                    <thead>
                        <tr>
                            <td>Name</td>
                            <td>Assignee</td>
                            <td>Start date</td>
                            <td>Due date</td>
                            <td>Is completed</td>
                        </tr>
                    </thead>
                    <tbody>
                        {%for item in project.tasks.all %}
                            <tr>
                                <td>{{item.name}}</td>
                                <td>{{item.assignee}}</td>
                                <td>{{item.start_date}}</td>
                                <td>{{item.due_date}}</td>
                                <td>{{item.is_completed}}</td>
                            </tr>
                        {%endfor%}
                    </tbody>
                </table>
            {%else%}
                <p>This project has no tasks</p>
            {%endif%}
        </div>
    </main>
{%endblock content%}

projects/templates/project_listview.html
{%extends 'base.html'%}
{%block content%}
    <main>
        <div>
            <h1>My Projects</h1>
            <p><a href="{%url 'create_project'%}">Create a new project</a></p>
            {%if project_list|length == 0%}
                <p>You are not assigned to any projects</p>
            {%else%}
                <table>
                    <thead>
                        <tr>
                            <td>Name</td>
                            <td>Number of tasks</td>
                        </tr>
                    </thead>
                    <tbody>
                        {%for item in project_list%}
                            <tr>
                                <td><a href="{% url 'show_project' item.pk%}">{{item.name}}</td>
                                    <td>{{item.tasks.all|length}}</td>
                                </tr>
                        {%endfor%}
                    </tbody>
                </table>
            {%endif%}
        </div>
    </main>
{%endblock content%}

tasks/templates/task_create.html
{%extends 'base.html'%}
{%block content%}
    <main>
        <div>
            <h1>Create a new task</h1>
            <form action="" method="POST">
                {% csrf_token %}
                {{form.as_p}}
                <button type="submit">Create</button>
            </form>
        </div>
    </main>
{%endblock content%}

tasks/templates/task_listview.html
{%extends 'base.html'%}
{%block content%}
    <main>
        <div>
            <h1>My Tasks</h1>
            {%if task_list|length > 0%}
                <table>
                    <thead>
                        <tr>
                            <th>Name</th>
                            <th>Start date</th>
                            <th>End date</th>
                            <th>Is completed</th>
                        </tr>
                    </thead>
                    <tbody>
                        {%for item in task_list%}
                            <tr>
                                <td>{{item.name}}</td>
                                <td>{{item.start_date}}</td>
                                <td>{{item.due_date}}</td>
                                <td>   {% if item.is_completed is True %}
                                    <p>Done<p>
                                {%else%}
                                    <form method="post" action='{% url "show_my_tasks" %}'>
                                        {% csrf_token %}
                                        <input type="hidden" name="is_completed" value="True">
                                        <button>Complete</button>
                                    </form>
                                {%endif%}
                                </td>
                            </tr>
                        {%endfor%}
                    </tbody>
                </table>
            {%else%}
                <p>You have no tasks</p>
            {%endif%}
        </div>
    </main>
{%endblock content%}